### ISSUE TITLE
Modificar objeto de invocación (indigitamenta) para que incluya tirada

### ISSUE THREAD

**Issue by Teotimus** [parvusdomus/custos#38]
Algunos indigitamenta requieren tirada (y varía en cada caso). Ver páginas 92-92 del manual en castellano.

**Comment by parvusdomus** [comment]
Añadida entrada para virtus en la ficha de indigitamentus, si su valor es distinto de ninguno en la pestaña magia, junto al nombre del objeto (izda) aparece un dado, si lo pulsas hace la tirada y gasta pietas.
