### ISSUE TITLE
Problemas detectados o pendientes

### ISSUE THREAD

**Issue by Yurian00** [parvusdomus/custos#49]
Buenas, haciendo pruebas con el sistema he visto lo siugiente:

No se pueden añadir los valores que la la provincia en Creatio. Aparece el valor en 0 pero no es un campo que se pueda editar/rellenar.

En la parte de inventario no sepuede añadir/editar nada.

Los valores negativos por oficio no se restan en los valores de la hoja.

Si puedo ayudarte con algo me dices.

**Comment by parvusdomus** [comment]
Buenos días Yurian00,

gracias por el feedback. Te comento cada punto.

- Para añadir la provincia en creatio tienes que crear un objeto provintia en la pestaña de items del interfaz de foundry (con sus valores correspontientes) y arrastrarlo a la casilla de provincia de la pestaña de creatio (lo que hará que se cargue el nombre de la provincia y sus valores en los campos correspondientes). 

- Para añadir cualquier objeto a inventario lo tienes que crearlo en items y arrastrarlo a la sección correspondiente al tipo de objeto que has creado.

- El oficio (junto con los atributos correspondientes) determina el valor de vida y pietas. He comprobado que se hace correctamente. No se si te refieres a otra cosa o estoy pasando por alto algo, me puedes desarrollar este punto e indicarme en qué página del manual re menciona, porque lo de valores negativos por oficio no me suena.

**Comment by Yurian00** [comment]
Perfecto con los objetos y provincias, con ese tema resuelto. Sin embargo, lo que me pasa en los oficios.

Luchador, debería sumar 3 a vida y restar 1 en pietas y aquí puedes ver que no aplica ningún cambio:
![image](https://github.com/user-attachments/assets/434bee35-6786-4249-851d-4ba34573cff3)

El Augur debería dar -1 a vida y +3 a pietas. La vida OK pero solo resta 2 a pietas:
![image](https://github.com/user-attachments/assets/561deb5e-29ec-48e5-b2c9-f0758a2cf736)

El explorador está OK

El erudito debería sumar 0 a vida y 2 a pietas y está restando 1 a vida y sumando OK los dos a pietas:
![image](https://github.com/user-attachments/assets/b15e3fb1-77ed-4c40-bcae-17b94b55735d)

El diplomático está OK

El asesino está OK

No se si soy solo yo, tengo descargada la última versión eso si.

**Comment by parvusdomus** [comment]
Ya veo lo que pasa. En el PDF en inglés vienen los valores que tú indicas:
![image](https://github.com/user-attachments/assets/62def1c4-1f0f-450b-b46a-6a06cd18d4b2)
pero en la versión en español (tanto en PDF como en físico) los valores que vienen son lo que he usado, que son otros:
![image](https://github.com/user-attachments/assets/0be9ae9a-d85e-4376-b2c3-998e7f74696e)

He escrito a Cursed Ink para que me confirmen cuales son los valores correctos.

**Comment by Yurian00** [comment]
Aaaaahmigo. Pos le voy a pinchar a Gaiska para que nos diga algo. Muchas gracias!!!
